all:
        hosts:
                gateway:
                        ansible_host: 10.0.0.254
                        ansible_ssh_user : itesciadmin

                dns:
                        ansible_host: 10.0.0.102
                        ansible_ssh_user : itescia

                backup: 
                        ansible_host: 10.0.0.101
                        ansible_ssh_user: itescia

                web-server: 
                        ansible_host: 10.0.0.19
                        ansible_ssh_user: itescia

