all:
        hosts:
                10.0.0.19
        vars:
                ansible_ssh_user: itescia
                ansible_ssh_pass: itescia

ns1:
        hosts:
                10.0.0.[101:102] :
        vars: 
          ansible_ssh_user: itescia
          ansible_ssh_pass : itescia 

gateway:
        hosts:
                10.0.0.254
        vars:
                ansible_ssh_user: itesciadmin
                ansible_ssh_pass: itescia

